In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
myarr = np.array(mylist)

In [6]:
type(myarr)

numpy.ndarray

In [7]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [8]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix) 
# numpy knows that this is a 2D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# Built-in functions
np.arange(0,10,)
# this is the equivalent to python built-in range function in numpy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((1,5))

array([[1., 1., 1., 1., 1.]])

In [18]:
# line space
np.linspace(0, 10,3)
# third parameters are size.

array([ 0.,  5., 10.])

In [19]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [21]:
# creates identity matrix 
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
# how to create random distributions of data
np.random.rand(1) # create an array from a uniform distribution over [0, 1)
# uniform distribution, numbers between 0 and 1 have the same likelihood.


array([0.32364633])

In [24]:
# pass in a shape, dont pass a tuple
np.random.rand(3,4)

array([[0.18573421, 0.09734116, 0.89525417, 0.06250671],
       [0.05560744, 0.89445217, 0.10648948, 0.08452817],
       [0.21712636, 0.23679192, 0.63735673, 0.76095993]])

In [25]:
# creates samples from a standart normal distribution
np.random.randn(10)

array([-0.0235483 ,  0.75343307,  0.51144264, -1.93557804,  0.48650848,
        0.60418172,  0.7788261 , -0.1703047 ,  0.07529511, -0.04079566])

In [26]:
np.random.randn(2,3)

array([[-0.02500761,  0.51485556,  0.19379701],
       [ 0.71726968,  1.72305842,  0.19915044]])

In [27]:
np.random.randint(0,101,4) # uniform dist.

array([54, 53, 85, 84])

In [29]:
np.random.randint(0,101,(4,5))

array([[68, 78, 25,  2, 42],
       [42, 68, 82, 70, 39],
       [50, 23, 10, 14, 75],
       [40, 69, 38, 61, 26]])

In [30]:
# useful to set a seed. set a random state so that random results can be reproduced.
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [31]:
arr = np.arange(0,25)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
arr.max()

24

In [35]:
arr.min()

0

In [39]:
arr.argmax() # returns back max element's index

24

In [38]:
arr.argmin() # returns back min element's index

0

In [40]:
arr.dtype

dtype('int32')

In [41]:
arr.shape

(25,)

In [42]:
arr = arr.reshape(5,5)

In [43]:
arr.shape

(5, 5)

In [44]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])