In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[0]

0

In [6]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[0:5] = 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [7]:
mylist = [1,2,3,4,5]

In [8]:
mylist[0:3] = 4

TypeError: can only assign an iterable

In [9]:
mylist[0:2] = [55, 78]

In [10]:
mylist

[55, 78, 3, 4, 5]

In [13]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [14]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [15]:
arr_2d.shape

(3, 3)

In [16]:
arr_2d[0]

array([ 5, 10, 15])

In [17]:
arr_2d[1][1]

25

In [18]:
arr_2d[1,1]

25

In [19]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [20]:
arr_2d[:2,1]

array([10, 25])

In [21]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [22]:
arr = np.arange(1,11)

In [23]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [25]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])