In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("Advertising.csv")

In [4]:
X = df.drop('sales', axis=1)

In [5]:
y = df['sales']

In [6]:
from sklearn.preprocessing import PolynomialFeatures

In [7]:
polynomial_converter = PolynomialFeatures(degree=3, include_bias=False)

In [8]:
poly_features = polynomial_converter.fit_transform(X)

In [9]:
X.shape

(200, 3)

In [10]:
poly_features.shape

(200, 19)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [13]:
X_train.shape

(140, 19)

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
scaler = StandardScaler()

In [16]:
scaler.fit(X_train) #do not use entire data set.

StandardScaler()

In [17]:
X_train = scaler.transform(X_train)

In [18]:
X_test = scaler.transform(X_test)

In [19]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [20]:
poly_features[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

In [21]:
from sklearn.linear_model import Ridge

In [22]:
ridge_model = Ridge(alpha=10)

In [23]:
ridge_model.fit(X_train, y_train)

Ridge(alpha=10)

In [24]:
test_predictions = ridge_model.predict(X_test)

In [25]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [26]:
MAE = mean_absolute_error(y_test, test_predictions)

In [27]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [28]:
MAE

0.5774404204714167

In [29]:
RMSE

0.894638646131965

In [30]:
from sklearn.linear_model import RidgeCV

In [31]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0), scoring='neg_mean_absolute_error')

In [32]:
ridge_cv_model.fit(X_train, y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_absolute_error')

In [33]:
ridge_cv_model.alpha_

0.1

In [34]:
from sklearn.metrics import SCORERS

In [35]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted'])

In [36]:
test_predictions = ridge_cv_model.predict(X_test)

In [37]:
MAE = mean_absolute_error(y_test, test_predictions)

In [38]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [39]:
MAE

0.4273774884351013

In [40]:
RMSE

0.6180719926948981

In [41]:
ridge_cv_model.coef_ # no more zeros

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

### LASSO - least absolute shrinkage and selection operator

In [42]:
from sklearn.linear_model import LassoCV

In [43]:
lasso_cv_model = LassoCV(eps=0.1,n_alphas=100, cv=5, max_iter=100)

In [44]:
lasso_cv_model.fit(X_train, y_train)

LassoCV(cv=5, eps=0.1, max_iter=100)

In [45]:
lasso_cv_model.alpha_

0.4943070909225832

In [46]:
test_predictions = lasso_cv_model.predict(X_test)

In [47]:
MAE = mean_absolute_error(y_test, test_predictions)

In [48]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [49]:
MAE

0.6541723161252867

In [50]:
RMSE

1.1308001022762548

In [51]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [52]:
from sklearn.linear_model import ElasticNetCV

In [66]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7, .9, .95, .99, 1], 
                             eps=0.001, n_alphas=100, max_iter=1000000)

In [77]:
elastic_model.fit(X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [78]:
elastic_model.l1_ratio_

1.0

In [79]:
elastic_model.alpha_

0.004943070909225833

In [80]:
test_predictions = elastic_model.predict(X_test)

In [81]:
MAE = mean_absolute_error(y_test, test_predictions)

In [82]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [84]:
RMSE

0.6063140748984043

In [83]:
MAE

0.4335034618590078